<a href="https://colab.research.google.com/github/GurkiratSarna/CE888-Decision-Making-UoE/blob/master/Lab_5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [15]:
#Upload file in sample_data folder
#https://github.com/GurkiratSarna/CE888-Decision-Making-UoE/blob/master/Lab_5/jester-data-1.csv
df = pd.read_csv("jester-data-1.csv", header=None)
print(df)

       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]


In [16]:
#Drop first column because it shows the number of jokes that have a score. i.e. not 99 in that row.
df=df.iloc[:,1:]
print(df)

         1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]


***Helper Function***

In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [17]:
arr=df.values
new_arr, idx = replace(arr, 0.1)
print(new_arr)

[[-7.82 99.   -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29 99.   ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]


***Latent Features***

In [18]:
n_latent_factors = 2

user_ratings = new_arr
print(user_ratings)
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
print(latent_user_preferences)
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
print(latent_item_features)

[[-7.82 99.   -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29 99.   ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]
[[0.79604766 0.54764081]
 [0.00215058 0.34214623]
 [0.8162629  0.23611982]
 ...
 [0.56186573 0.87299184]
 [0.13908374 0.64680485]
 [0.93089529 0.02091865]]
[[0.39856457 0.69149244]
 [0.316678   0.76132064]
 [0.30164077 0.15026837]
 [0.26829245 0.13627137]
 [0.97669743 0.91596871]
 [0.00845918 0.70336317]
 [0.0486003  0.40038619]
 [0.7986995  0.11971912]
 [0.20425659 0.15385999]
 [0.1921205  0.2890581 ]
 [0.95071876 0.39496748]
 [0.78349293 0.7057599 ]
 [0.67848069 0.04102044]
 [0.28927292 0.3765366 ]
 [0.91372822 0.15364634]
 [0.21965418 0.88606401]
 [0.22688662 0.08263778]
 [0.62336259 0.44161245]
 [0.54646516 0.97647337]
 [0.87472931 0.10859292]
 [0.64182607 0.45949348]
 [0.36536232 0.04470527]
 [0.91999321 0.44723515]
 [0.6

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    
#change nan condition to not equal to 99
#change 10000 modulo operation to 10, for 100 sgd() iterations
def sgd(iterations=300000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating != 99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)

In [20]:
#sgd()
#sgd(100)
#sgd(20) 
'''814.0265993739114
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: overflow encountered in multiply
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in subtract
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:33: RuntimeWarning: overflow encountered in square'''
#sgd(15)
'''nan'''
sgd(100)

26.20725955417107
23.185096276637957
20.939336677841517
18.098879195905997
17.30984047627002
17.157623518970503
17.110060638677844
17.09299124206495
17.0866401702722
17.084366689254836


In [21]:
pred = latent_user_preferences.dot(latent_item_features.T)
print(pred)

[[-4.18090388 -4.49630014 -5.94139565 ... -2.77078677 -6.47759766
  -2.90813501]
 [ 2.91856346  3.10276217  3.73165157 ...  2.4348532   3.8911522
   2.65666824]
 [ 6.86949659  7.18781207  7.45098927 ...  7.334918    7.13823213
   8.26047441]
 ...
 [-0.63941429 -0.68525093 -0.88092201 ... -0.4571471  -0.94860022
  -0.48655224]
 [-1.92047726 -2.07789731 -2.87417895 ... -1.09814769 -3.19539319
  -1.11731821]
 [ 2.7309675   2.81352048  2.45352153 ...  3.52831923  2.06646517
   4.05030137]]


In [0]:
values = [zip(user_ratings[i], pred[i]) for i in range(pred.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [23]:
# the first number is the orginal value from the jester-ata-1.csv dataset, 
# the second number is the predicted value
print(comparison_data)

                               1    ...                          100
0      (-7.82, -4.180903879406694)  ...   (99.0, -2.908135005965566)
1       (4.08, 2.9185634637360645)  ...    (1.07, 2.656668235540103)
2       (99.0, 6.8694965854024685)  ...    (99.0, 8.260474406705367)
3        (99.0, 2.310381601169257)  ...   (99.0, 3.5210446475226265)
4         (8.5, 2.789276638707742)  ...     (1.6, 4.243880734869256)
...                            ...  ...                          ...
24978    (0.44, 2.383182916718898)  ...   (99.0, 3.9571906748087526)
24979   (9.13, 2.4147444266335096)  ...   (8.45, 1.6072260841057768)
24980  (99.0, -0.6394142913639729)  ...  (99.0, -0.4865522432230538)
24981  (99.0, -1.9204772647299797)  ...  (99.0, -1.1173182123766063)
24982    (2.43, 2.730967498186018)  ...    (99.0, 4.050301369246524)

[24983 rows x 100 columns]


In [24]:
#Calculate the performance (e.g., MSE) of the algorithm on the validation dataset
error=(pred[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse = sum(error)/len(error)
mse

18.064931955812327

***Changing hyper-parameters (learning rate, number of iterations of SVD, number of latent factors)***

learning rate changed to 0.0005

features as 3

30 iterations

In [0]:
# changed factors to 3
n_latent_factors2 = 3

user_ratings2 = new_arr
user_ratings2
# Initialise as random values
latent_user_preferences2 = np.random.random((user_ratings2.shape[0], n_latent_factors2))
latent_item_features2 = np.random.random((user_ratings2.shape[1], n_latent_factors2))

In [0]:
def predict_rating2(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference2 = latent_user_preferences2[user_id]
    item_preference2 = latent_item_features2[item_id]
    return user_preference2.dot(item_preference2)

#changed training to 0.0005
def train2(user_id, item_id, rating, alpha=0.0005):
    
    #print item_id
    prediction_rating2 = predict_rating2(user_id, item_id)
    err =  prediction_rating2 - rating
    #print err
    user_pref_values2 = latent_user_preferences2[user_id][:]
    latent_user_preferences2[user_id] -= alpha * err * latent_item_features2[item_id]
    latent_item_features2[item_id] -= alpha * err * user_pref_values2
    return err
    

def sgd2(iterations=30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences2.shape[0]):
            for item_id in range(latent_item_features2.shape[0]):
                rating = user_ratings2[user_id][item_id]
                if (rating!=99):
                    err = train2(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)

In [27]:
sgd2(30)

25.037484207227152
24.15262747411831
23.320167846026287
22.22530373587896
20.48248676653629
18.70988649404498
17.885560981387645
17.605988483372585
17.486512782390204
17.422560013208273
17.383638250573153
17.357141999545252
17.33589755437039
17.31444303722884
17.287508719403682
17.24955374976399
17.195550774346383
17.123326617994554
17.036344322754502
16.94377115965112
16.856221097655997
16.780875603292575
16.72032215591231
16.674303983760954
16.64147299045642
16.620178870889102
16.60871797462228
16.605450361803435
16.60889801883146
16.617814208366035


In [28]:
pred2 = latent_user_preferences2.dot(latent_item_features2.T)
pred2

array([[-3.5215062 , -3.80196846, -5.19135466, ..., -2.39471078,
        -6.01889251, -2.73907104],
       [ 3.3535479 ,  4.74586751,  4.49092562, ...,  3.06157656,
         2.85508349,  3.69327503],
       [ 6.84989855,  6.89082162,  7.50233728, ...,  7.63859838,
         7.63641991,  8.42199373],
       ...,
       [-0.14353892,  1.37895494, -0.04712361, ...,  0.03677952,
        -2.66932399,  0.36706196],
       [-1.10296848,  0.75230231, -1.60579805, ..., -0.35586304,
        -5.31625515, -0.01075684],
       [ 3.24956268,  3.33535015,  3.13362947, ...,  4.144325  ,
         2.68916317,  4.56946881]])

In [0]:
values2 = [zip(user_ratings2[i], pred2[i]) for i in range(pred2.shape[0])]
comparison_data2 = pd.DataFrame(values2)
comparison_data2.columns = df.columns

In [31]:
comparison_data2

1    ...                            100
0      (-7.82, -3.521506203143267)  ...    (99.0, -2.7390710404189726)
1        (4.08, 3.353547903038124)  ...     (1.07, 3.6932750312970186)
2        (99.0, 6.849898552783585)  ...      (99.0, 8.421993725128242)
3        (99.0, 2.526256550558238)  ...       (99.0, 4.37264201913314)
4        (8.5, 2.7092782793887187)  ...       (1.6, 4.122831824422585)
...                            ...  ...                            ...
24978    (0.44, 3.031161946326063)  ...      (99.0, 4.367563827460975)
24979   (9.13, 3.1388696323315717)  ...     (8.45, 3.1985527573428385)
24980   (99.0, -0.143538924406729)  ...    (99.0, 0.36706195999090535)
24981   (99.0, -1.102968484446199)  ...  (99.0, -0.010756835981125847)
24982   (2.43, 3.2495626764675682)  ...      (99.0, 4.569468808499675)

[24983 rows x 100 columns]

In [32]:
error2=(pred2[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse2 = sum(error2)/len(error2)
mse2

17.711182783492998

***Changing hyper-parameters (learning rate, number of iterations of SVD, number of latent factors)- PART 2***

Learning rate is same as 0.0001

features changed from 2 to 3

200 iterations

In [0]:
# changed factors to 3
n_latent_factors3 = 3

user_ratings3 = new_arr
user_ratings3
# Initialise as random values
latent_user_preferences3 = np.random.random((user_ratings3.shape[0], n_latent_factors3))
latent_item_features3 = np.random.random((user_ratings3.shape[1], n_latent_factors3))

In [0]:
def predict_rating3(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference3 = latent_user_preferences3[user_id]
    item_preference3 = latent_item_features3[item_id]
    return user_preference3.dot(item_preference3)

#changed training to 0.0001 - original
def train3(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating3 = predict_rating3(user_id, item_id)
    err =  prediction_rating3 - rating
    #print err
    user_pref_values3 = latent_user_preferences3[user_id][:]
    latent_user_preferences3[user_id] -= alpha * err * latent_item_features3[item_id]
    latent_item_features3[item_id] -= alpha * err * user_pref_values3
    return err
    

def sgd3(iterations=30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences3.shape[0]):
            for item_id in range(latent_item_features3.shape[0]):
                rating = user_ratings3[user_id][item_id]
                if (rating!=99):
                    err = train3(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)

In [39]:
sgd3(200)

25.956319221143612
23.678479041312457
21.172858322643496
17.872837935238717
17.31988709081891
17.14902194128329
17.014992312267623
16.84280784097936
16.644162595538035
16.480018767340173
16.368784544580286
16.297904825998163
16.254192403789013
16.22799113059757
16.21256489819733
16.2035407149454
16.198264913376608
16.19519171406006
16.193434275134816
16.192482315344556


In [40]:
pred3 = latent_user_preferences3.dot(latent_item_features3.T)
pred3

array([[-4.37933873, -4.56921453, -6.01712874, ..., -2.27952469,
        -6.04975561, -2.4900635 ],
       [ 1.94395268,  2.28324536,  3.26403531, ...,  2.87399857,
         4.33403513,  2.94573987],
       [ 7.6680156 ,  7.81641751,  7.82558139, ...,  6.47471657,
         6.36619938,  7.55445898],
       ...,
       [-2.22274343, -1.76774979, -1.1125093 , ...,  1.76367746,
         1.3710949 ,  1.40899307],
       [-2.03687947, -2.20982738, -3.22216685, ..., -1.29804275,
        -3.6626229 , -1.31967709],
       [ 1.53975722,  1.96359769,  2.10785317, ...,  4.81482359,
         3.3201441 ,  5.11387738]])

In [0]:
values3 = [zip(user_ratings3[i], pred3[i]) for i in range(pred3.shape[0])]
comparison_data3 = pd.DataFrame(values3)
comparison_data3.columns = df.columns

In [42]:
comparison_data3

1    ...                          100
0       (-7.82, -4.37933873374446)  ...   (99.0, -2.490063504017125)
1        (4.08, 1.943952679266347)  ...   (1.07, 2.9457398666068615)
2        (99.0, 7.668015602019704)  ...    (99.0, 7.554458981116796)
3       (99.0, 0.7912708523605932)  ...     (99.0, 4.87907416308439)
4        (8.5, 2.5257590015649334)  ...      (1.6, 4.40116004561204)
...                            ...  ...                          ...
24978  (0.44, -0.4014193497799445)  ...    (99.0, 5.155819021980005)
24979    (9.13, 2.113689735701361)  ...   (8.45, 1.6989885626036672)
24980   (99.0, -2.222743430150409)  ...   (99.0, 1.4089930749113102)
24981  (99.0, -2.0368794677215103)  ...  (99.0, -1.3196770905375002)
24982   (2.43, 1.5397572186783564)  ...    (99.0, 5.113877376720794)

[24983 rows x 100 columns]

In [43]:
error3=(pred3[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse3 = sum(error3)/len(error3)
mse3

17.7158597963128

With change in features from 2 to 3 and increase in iterations from 100 to 200 the MSE reduced with the same learning rate

The learning rate is similar when the learning rate was increased to 0.0005 with less iterations and increased features