<a href="https://colab.research.google.com/github/GurkiratSarna/CE888-Decision-Making-UoE/blob/master/Lab_5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [44]:
#Upload file in sample_data folder
#https://github.com/GurkiratSarna/CE888-Decision-Making-UoE/blob/master/Lab_5/jester-data-1.csv
df = pd.read_csv("jester-data-1.csv", header=None)
print(df)

       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]


In [45]:
#Drop first column because it shows the number of jokes that have a score. i.e. not 99 in that row.
df=df.iloc[:,1:]
print(df)

         1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]


***Helper Function***

In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [47]:
arr=df.values
new_arr, idx = replace(arr, 0.1)
print(new_arr)

[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]


***Latent Features***

In [48]:
n_latent_factors = 2

user_ratings = new_arr
print(user_ratings)
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
print(latent_user_preferences)
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
print(latent_item_features)

[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]
[[0.68843301 0.42818895]
 [0.88647331 0.88876591]
 [0.1335714  0.40920731]
 ...
 [0.09640848 0.46422415]
 [0.15701589 0.89442726]
 [0.37178776 0.0967654 ]]
[[0.58482467 0.39451139]
 [0.30978943 0.9759948 ]
 [0.61467374 0.31444604]
 [0.49826318 0.92204384]
 [0.66044149 0.58078424]
 [0.32264998 0.98837888]
 [0.77255341 0.66541298]
 [0.98280144 0.5521278 ]
 [0.45874516 0.66047882]
 [0.94449562 0.60433714]
 [0.14141697 0.39438529]
 [0.13614236 0.40589426]
 [0.78074261 0.47351701]
 [0.65609008 0.83947675]
 [0.59580151 0.67041289]
 [0.24472068 0.96807376]
 [0.30507067 0.93554669]
 [0.8071338  0.39788701]
 [0.11513836 0.98269536]
 [0.27218091 0.83985563]
 [0.58839765 0.58063783]
 [0.61554618 0.28940751]
 [0.37627672 0.84435843]
 [0.0

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    
#change nan condition to not equal to 99
#change 10000 modulo operation to 10, for 100 sgd() iterations
def sgd(iterations=300000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating != 99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)

In [50]:
#sgd()
#sgd(100)
#sgd(20) 
'''814.0265993739114
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: overflow encountered in multiply
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in subtract
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:33: RuntimeWarning: overflow encountered in square'''
#sgd(15)
'''nan'''
sgd(100)

26.228505242856187
23.23084772527652
20.270068627787087
17.685633694552575
17.260704572566112
17.152967496188985
17.11458356501147
17.09952630519723
17.093418108273926
17.091002897919175


In [51]:
pred = latent_user_preferences.dot(latent_item_features.T)
print(pred)

[[-3.96736208 -4.14953323 -5.68879356 ... -2.57760959 -6.17501353
  -2.67397795]
 [ 2.84150747  2.96111195  3.53009482 ...  2.50033463  3.63403822
   2.74226459]
 [ 7.06683297  7.34329426  7.72800196 ...  7.48186914  7.51466656
   8.4175103 ]
 ...
 [-1.76384761 -1.84165385 -2.36967982 ... -1.33766658 -2.51426572
  -1.43117555]
 [-2.79762966 -2.92546691 -3.98033063 ... -1.85510977 -4.30919803
  -1.93297112]
 [ 2.7139898   2.80936502  2.42715902 ...  3.52326802  2.10254102
   4.05436671]]


In [0]:
values = [zip(user_ratings[i], pred[i]) for i in range(pred.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [53]:
# the first number is the orginal value from the jester-ata-1.csv dataset, 
# the second number is the predicted value
print(comparison_data)

                                1    ...                          100
0      (-7.82, -3.9673620754078383)  ...   (99.0, -2.673977945618399)
1        (4.08, 2.8415074717588125)  ...   (1.07, 2.7422645935222945)
2         (99.0, 7.066832971186844)  ...    (99.0, 8.417510302739666)
3         (99.0, 2.025628085741939)  ...   (99.0, 2.9725968720491824)
4         (8.5, 2.9525052687227338)  ...     (1.6, 4.376262389961841)
...                             ...  ...                          ...
24978    (0.44, 2.0705754711494926)  ...   (7.43, 3.6459847864266792)
24979    (99.0, 2.3657042681221196)  ...   (8.45, 1.5858024620385383)
24980    (99.0, -1.763847608186481)  ...   (99.0, -1.431175551970172)
24981    (99.0, -2.797629659085228)  ...  (99.0, -1.9329711160235368)
24982    (2.43, 2.7139897985506445)  ...    (99.0, 4.054366711505592)

[24983 rows x 100 columns]


In [54]:
#Calculate the performance (e.g., MSE) of the algorithm on the validation dataset
error=(pred[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse = sum(error)/len(error)
mse

18.012805935812626

***Changing hyper-parameters (learning rate, number of iterations of SVD, number of latent factors)***

In [0]:
# changed factors to 3
n_latent_factors2 = 3

user_ratings2 = new_arr
user_ratings2
# Initialise as random values
latent_user_preferences2 = np.random.random((user_ratings2.shape[0], n_latent_factors2))
latent_item_features2 = np.random.random((user_ratings2.shape[1], n_latent_factors2))

In [0]:
def predict_rating2(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference2 = latent_user_preferences2[user_id]
    item_preference2 = latent_item_features2[item_id]
    return user_preference2.dot(item_preference2)

#changed training to 0.0005
def train2(user_id, item_id, rating, alpha=0.0005):
    
    #print item_id
    prediction_rating2 = predict_rating2(user_id, item_id)
    err =  prediction_rating2 - rating
    #print err
    user_pref_values2 = latent_user_preferences2[user_id][:]
    latent_user_preferences2[user_id] -= alpha * err * latent_item_features2[item_id]
    latent_item_features2[item_id] -= alpha * err * user_pref_values2
    return err
    

def sgd2(iterations=30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences2.shape[0]):
            for item_id in range(latent_item_features2.shape[0]):
                rating = user_ratings2[user_id][item_id]
                if (rating!=99):
                    err = train2(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)

In [58]:
sgd2(30)

25.07329232534956
24.191500292669833
23.398320320855273
22.480959682456763
21.104411939852973
19.280237367859673
18.09575234473954
17.65953629881641
17.482385568286084
17.38012792288339
17.299936427401708
17.220934660608027
17.13441433632681
17.04086293639446
16.947801335912185
16.864413431956756
16.796264016922827
16.744183279449658
16.706251959788116
16.679825068164032
16.662493915573084
16.652332757612932
16.647874390661663
16.648022153046
16.651964114192708
16.659104001077537
16.66900879739376
16.68136978852732
16.695973811120535
16.712682142570287


In [59]:
pred2 = latent_user_preferences2.dot(latent_item_features2.T)
pred2

array([[-2.2988374 , -2.67624814, -4.66535633, ..., -3.0184998 ,
        -7.49553926, -2.88079392],
       [ 1.57456118,  1.79600198,  2.44192445, ...,  2.39133389,
         3.58781086,  2.43040201],
       [ 7.11000947,  7.46551963,  7.8609213 , ...,  7.35419793,
         7.94656135,  8.03293358],
       ...,
       [-4.15412175, -3.78610263, -3.91045285, ...,  0.73989147,
        -1.29147954,  0.28693253],
       [-3.40481631, -3.41914829, -4.59281881, ..., -1.23243678,
        -4.7974156 , -1.38747199],
       [ 2.87816932,  3.13139342,  2.89620615, ...,  4.31277727,
         3.0741379 ,  4.65280058]])

In [0]:
values2 = [zip(user_ratings2[i], pred2[i]) for i in range(pred2.shape[0])]
comparison_data2 = pd.DataFrame(values2)
comparison_data2.columns = df.columns

In [39]:
comparison_data2

1    ...                           100
0      (-7.82, -3.2244385009311727)  ...    (99.0, -2.312608221303939)
1        (4.08, 3.5746782968676936)  ...    (1.07, 3.5719502116781086)
2          (99.0, 6.47274474719863)  ...     (99.0, 8.367561701491619)
3          (99.0, 3.33929577618732)  ...     (99.0, 4.069168726086897)
4          (8.5, 2.921488247583992)  ...      (1.6, 4.463768705865874)
...                             ...  ...                           ...
24978    (0.44, 2.7219612935813435)  ...     (7.43, 4.521966982045066)
24979    (9.13, 3.5120955045158606)  ...    (99.0, 2.8415733976054995)
24980  (99.0, -0.28846209474839507)  ...  (99.0, -0.26441261632434687)
24981   (99.0, -1.6982139135163947)  ...   (99.0, -1.1588784210226684)
24982     (2.43, 2.836058514805402)  ...     (99.0, 4.507854349532662)

[24983 rows x 100 columns]

In [40]:
error2=(pred2[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse2 = sum(error2)/len(error2)
mse2

17.763839816708067

***Changing hyper-parameters (learning rate, number of iterations of SVD, number of latent factors)- PART 2***

In [0]:
# changed factors to 3
n_latent_factors3 = 3

user_ratings3 = new_arr
user_ratings3
# Initialise as random values
latent_user_preferences3 = np.random.random((user_ratings3.shape[0], n_latent_factors3))
latent_item_features3 = np.random.random((user_ratings3.shape[1], n_latent_factors3))

In [0]:
def predict_rating3(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference3 = latent_user_preferences3[user_id]
    item_preference3 = latent_item_features3[item_id]
    return user_preference3.dot(item_preference3)

#changed training to 0.0001 - original
def train3(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating3 = predict_rating3(user_id, item_id)
    err =  prediction_rating3 - rating
    #print err
    user_pref_values3 = latent_user_preferences3[user_id][:]
    latent_user_preferences3[user_id] -= alpha * err * latent_item_features3[item_id]
    latent_item_features3[item_id] -= alpha * err * user_pref_values3
    return err
    

def sgd3(iterations=30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences3.shape[0]):
            for item_id in range(latent_item_features3.shape[0]):
                rating = user_ratings3[user_id][item_id]
                if (rating!=99):
                    err = train3(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1000) == 0:
            print(mse)

In [0]:
sgd3()