<a href="https://colab.research.google.com/github/GurkiratSarna/CE888-Decision-Making-UoE/blob/master/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib
import pandas as pd
import numpy as np
import seaborn as sbs

In [0]:
# Bootstraping

In [0]:
df=pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/customers.csv')

In [0]:
data = df.values.T[1]

In [7]:
print(data)

[ 2.  8. 20. 13.  5.  9. 10.  8. 22. 10.  2.  4.  7.  9.]


In [9]:
data.shape

(14,)

In [0]:
# Checking the notes from the lecture, create here your own bootstrap function:
# 1. Create an array of samples of shape (n_iterations, sample_size) - this creates a 2d array of num of rows different everytime
# 2. Calculate and save the mean of the array (this is "data_mean" that is returned by the function)
# 3. In each iteration:
# 3.1 Get the data corresponding to that iteration (new_samples[iteration, :])
# 3.2 Calculate the mean of the iteration data and store it
# (At this point you should have an array of n_iterations values)
# 4. Calculate the lower and upper bounds for a 95% CI (hint: check the percentile function on Numpy)
# 5. Return data_mean, and the lower and upper bounds of your interval
def boostrap_mean(sample, sample_size, n_iterations):
	# <---INSERT YOUR CODE HERE--->
  bstraplist=np.random.choice(sample,(n_iterations,sample_size),replace=True)
  print(bstraplist)
  
  data_mean=np.mean(bstraplist)
  mean_list=[]
  for i in range(len(bstraplist)):
    new_sample=bstraplist[i,:]
    sample_mean=np.mean(new_sample)
    mean_list.append(sample_mean)
    print(new_sample)
    print(sample_mean)
  print(mean_list)
  lower=min(mean_list)
  upper=max(mean_list)
  print(lower,"\t",upper)
  print(data_mean)
  print("----"*20)

	return data_mean, lower, upper

In [38]:

# Call your bootstrap function and plot the results

boots = []
#for i in range(100, 100000, 1000):
for i in range(5, 10): 
    boots = boostrap_mean(data, data.shape[0], i)
    boots.append([i, boot[0], "mean"])
    boots.append([i, boot[1], "lower"])
    boots.append([i, boot[2], "upper"])

df_boot = pd.DataFrame(boots, columns=['Boostrap Iterations', 'Mean', "Value"])
sns_plot = sns.lmplot(df_boot.columns[0], df_boot.columns[1], data=df_boot, fit_reg=False, hue="Value")

sns_plot.axes[0, 0].set_ylim(0,)
sns_plot.axes[0, 0].set_xlim(0, 100000)

#sns_plot.savefig("bootstrap_confidence.png", bbox_inches='tight')
#sns_plot.savefig("bootstrap_confidence.pdf", bbox_inches='tight')

[[ 9. 20.  8. 10.  4. 10. 10.  2.  7. 10.  2. 13.  9. 13.]
 [ 8. 20.  9.  7.  9.  9. 20.  7. 13. 10. 10. 10. 10.  9.]
 [ 8.  2.  2.  8.  4.  9.  9.  5.  4.  5. 10.  5.  2. 20.]
 [ 7.  8. 10.  4.  4. 10. 10. 13.  9.  2. 20. 13. 13.  2.]
 [13. 13.  5.  8.  8.  9.  9.  7.  5.  5. 10.  7. 13. 13.]]
[ 9. 20.  8. 10.  4. 10. 10.  2.  7. 10.  2. 13.  9. 13.]
9.071428571428571
[ 8. 20.  9.  7.  9.  9. 20.  7. 13. 10. 10. 10. 10.  9.]
10.785714285714286
[ 8.  2.  2.  8.  4.  9.  9.  5.  4.  5. 10.  5.  2. 20.]
6.642857142857143
[ 7.  8. 10.  4.  4. 10. 10. 13.  9.  2. 20. 13. 13.  2.]
8.928571428571429
[13. 13.  5.  8.  8.  9.  9.  7.  5.  5. 10.  7. 13. 13.]
8.928571428571429
[9.071428571428571, 10.785714285714286, 6.642857142857143, 8.928571428571429, 8.928571428571429]
6.642857142857143 	 10.785714285714286
8.871428571428572
--------------------------------------------------------------------------------
[[ 2.  2.  8.  8. 13.  7. 10.  7.  4. 22.  4. 22.  8.  2.]
 [ 5. 10. 13.  7.  7.  2.  7.